export default tutorData = [
    {
      "id": 1,
      "name": "John Smith",
      "email": "john.smith@example.com",
      "username": "jsmith",
      "profile_image": "https://randomuser.me/api/portraits/men/1.jpg",
      "phone": "+1-555-123-4567",
      "country": "United States",
      "age": 30,
      "gender" : "Male",
      "bio": "I'm a computer science teacher with a passion for programming and a commitment to helping students learn.",
      "skills": ["JavaScript", "React", "Node.js"]
    },
    {
      "id": 2,
      "name": "Jane Doe",
      "email": "jane.doe@example.com",
      "username": "jdoe",
      "profile_image": "https://randomuser.me/api/portraits/women/2.jpg",
      "phone": "+1-555-234-5678",
      "country": "Canada",
      "age": 40,
      "gender" : "Female",
      "bio": "As a computer teacher, I enjoy showing my students how to use technology to solve real-world problems",
      "skills": ["Python", "Django", "SQL"]
    },
    {
      "id": 3,
      "name": "Bob Johnson",
      "email": "bob.johnson@example.com",
      "username": "bjohnson",
      "profile_image": "https://randomuser.me/api/portraits/men/3.jpg",
      "phone": "+1-555-345-6789",
      "country": "Australia",
      "age": 44,
      "gender" : "Female",
      "bio": "I'm a dedicated computer teacher with a focus on developing my students' technical skills and critical thinking abilities.",
      "skills": ["Ruby", "Rails", "PostgreSQL"]
    },
    {
      "id": 4,
      "name": "Emily Davis",
      "email": "emilydavis@example.com",
      "username": "emilydavis",
      "profile_image": "https://randomuser.me/api/portraits/women/4.jpg",
      "phone": "+1-555-456-7890",
      "age": 25,
      "gender" : "Male",
      "country": "United Kingdom",
      "bio": "Teaching computer science is my calling, and I love helping students discover the power of technology.",
      "skills": ["Java", "Spring Boot", "AWS"]
    },
    {
      "id": 5,
      "name": "David Kim",
      "email": "davidkim@example.com",
      "username": "davidkim",
      "profile_image": "https://randomuser.me/api/portraits/men/5.jpg",
      "phone": "+1-555-567-8901",
      "country": "Canada",
      "age": 18,
      "gender" : "Female",
      "bio": "As a computer teacher, I strive to create a classroom environment that encourages curiosity, creativity, and collaboration.",
      "skills": ["Python", "Django", "SQL"]
    },
    {
      "id": 6,
      "name": "Alex Wong",
      "email": "alex.wong@example.com",
      "username": "awong",
      "profile_image": "https://randomuser.me/api/portraits/men/5.jpg",
      "phone": "+1-555-567-8901",
      "country": "Canada",
      "age": 20,
      "gender" : "Male",
      "bio": "I'm a computer science teacher with a wealth of experience in both industry and academia",
      "skills": ["PHP", "Laravel", "MongoDB"]
    },
    {
      "id": 7,
      "name": "Grace Lee",
      "email": "grace.lee@example.com",
      "username": "glee",
      "profile_image": "https://randomuser.me/api/portraits/women/6.jpg",
      "phone": "+1-555-678-9012",
      "country": "United States",
      "age": 40,
      "gender" : "Female",
      "bio": "I believe that computer science education is essential for the next generation, and I'm proud to be a part of it.",
      "skills": ["C++", "OpenGL", "Firebase"]
    },
    {
      "id": 8,
      "name": "John Doe",
      "email": "johndoe@example.com",
      "username": "johndoe",
      "profile_image": "https://example.com/profiles/johndoe.png",
      "phone": "+1 (555) 123-4567",
      "country": "United States",
      "age": 22,
      "gender" : "Male",
      "bio": "My goal as a computer teacher is to inspire and empower my students to pursue their passions and achieve their goals",
      "skills": ["DataBase", "Computer Networks", "Machine Learning"]
    },
    {
      "id": 9,
      "name": "Jane Smith",
      "email": "janesmith@example.com",
      "username": "janesmith",
      "profile_image": "https://example.com/profiles/janesmith.png",
      "phone": "+1 (555) 987-6543",
      "country": "Canada",
      "age": 25,
      "gender" : "Female",
      "bio": "As a computer teacher, I'm committed to providing my students with the skills and knowledge they need to succeed in a rapidly changing world",
      "skills": ["Java", "Python", "JavaScript"]
    },
    {
      "id": 10,
      "name": "David Lee",
      "email": "davidlee@example.com",
      "username": "davidlee",
      "profile_image": "https://example.com/profiles/davidlee.png",
      "phone": "+44 20 1234 5678",
      "country": "United Kingdom",
      "age": 35,
      "gender" : "Male",
      "bio": "I'm a computer science teacher who believes that technology has the power to transform education and improve lives",
      "skills": ["Cybersecurity", "Network Engineering", "Ethical Hacking"]
    },
    {
      "id": 11,
      "name": "Maria Martinez",
      "email": "mariamartinez@example.com",
      "username": "mariamartinez",
      "profile_image": "https://example.com/profiles/mariamartinez.png",
      "phone": "+52 55 1234 5678",
      "country": "Mexico",
      "age": 33,
      "gender" : "Female",
      "bio": "I am a Spanish teacher with experience teaching both beginners and advanced students.",
      "skills": ["MySQL", "Oracle", "C++", "PHP"]
    },
    {
      "id": 12,
      "name": "James Wilson",
      "email": "jameswilson@example.com",
      "username": "jameswilson",
      "profile_image": "https://example.com/profiles/jameswilson.png",
      "phone": "+61 2 1234 5678",
      "country": "Australia",
      "age": 40,
      "gender" : "Female",
      "bio": "As a computer teacher, I'm passionate about helping students develop their critical thinking, problem-solving, and communication skills.",
      "skills": ["Machine Learning", "Artificial Intelligence", "Data Analysis", "Predictive Modeling"]
    },
    {
      "id": 13,
      "name": "Karen Davis",
      "email": "karendavis@example.com",
      "username": "karendavis",
      "profile_image": "https://example.com/profiles/karendavis.png",
      "phone": "+1 (555) 555-1234",
      "country": "United States",
      "age": 27,
      "gender" : "Male",
      "bio": "My mission as a computer teacher is to inspire my students to become lifelong learners and creators in the digital age",
      "skills": ["Java", "Python", "HTML", "CSS", "JavaScript"]
    },
    {
      "id": 14,
      "name": "Alice Lee",
      "email": "alice.lee@example.com",
      "username": "alicelee",
      "profile_image": "https://example.com/profiles/alicelee.jpg",
      "phone": "+1 555-555-5555",
      "country": "Canada",
      "age": 55,
      "gender" : "Male",
      "bio": "I'm a computer science teacher with a focus on web development. I love teaching my students how to build responsive, dynamic websites.",
      "skills": ["HTML", "CSS", "JavaScript", "React", "Node.js"]
    },
    {
      "id": 15,
      "name": "David Chen",
      "email": "david.chen@example.com",
      "username": "davidchen",
      "profile_image": "https://example.com/profiles/davidchen.jpg",
      "phone": "+86 10 5555 5555",
      "country": "China",
      "age": 38,
      "gender" : "Female",
      "bio": "I'm a computer science teacher with expertise in artificial intelligence. I enjoy teaching my students how to apply machine learning algorithms to real-world problems.",
      "skills": ["Machine Learning", "Python", "Data Science", "Deep Learning"]
    },
    {
      "id": 16,
      "name": "Maria Garcia",
      "email": "maria.garcia@example.com",
      "username": "mariagarcia",
      "profile_image": "https://example.com/profiles/mariagarcia.jpg",
      "phone": "+34 91 555 5555",
      "country": "Spain",
      "age": 38,
      "gender" : "Male",
      "bio": "I'm a computer science teacher who values collaboration and teamwork, both in the classroom and in the broader community.",
      "skills": ["Machine Learning", "Python", "Data Science", "Deep Learning"]
    },
    {
      "id": 17,
      "name": "Emily Wong",
      "email": "emilywong@gmail.com",
      "username": "emilywong",
      "profile_image": "https://example.com/emilywong.png",
      "phone": "+86 10 1234 5678",
      "country": "China",
      "age": 36,
      "gender" : "Female",
      "bio": "I am a computer science teacher who is passionate about teaching students how to code. I believe that anyone can learn to code with the right guidance and support.",
      "skills": ["Java", "Python", "C++"]
    },
    {
      "id": 18,
      "name": "Mohamed Ahmed",
      "email": "mohamedahmed@gmail.com",
      "username": "mohamedahmed",
      "profile_image": "https://example.com/mohamedahmed.png",
      "phone": "+20 2 1234 5678",
      "country": "Egypt",
      "age": 19,
      "gender" : "Female",
      "bio": "I am a computer science teacher with a focus on cybersecurity. I enjoy teaching students how to protect themselves and their organizations from cyber threats.",
      "skills": ["Python", "Linux", "Penetration testing"]
    },
    {
      "id": 19,
      "name": "Maria Rodriguez",
      "email": "mariarodriguez@gmail.com",
      "username": "mariarodriguez",
      "profile_image": "https://example.com/mariarodriguez.png",
      "phone": "+52 55 1234 5678",
      "country": "Mexico",
      "age": 40,
      "gender" : "Female",
      "bio": "I am a computer science teacher who specializes in data science. I enjoy teaching students how to analyze",
      "skills": ["Machine Learning", "Python", "Data Science", "Deep Learning"]
    },
    {
      "id": 20,
      "name": "Andrei Petrov",
      "email": "andrei.petrov@example.com",
      "username": "andreipetrov",
      "profile_image": "https://via.placeholder.com/150",
      "phone": "+7 123 456-7890",
      "country": "Russia",
      "age": 50,
      "gender" : "Male",
      "bio": "Andrei is a computer teacher with expertise in software development and web programming. He has experience teaching courses on web development frameworks such as React and Angular.",
      "skills": ["Software Development", "Web Programming", "React", "Angular"]
    }
  ]